spring:
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  data:
    mongodb:
      database: ${spring.application.name}
      grid-fs-database: ${spring.application.name}
  application:
    name: greedy
  main:
    banner-mode: 'OFF'
  mvc:
    favicon:
      enabled: true
endpoints: # disable actuator in production
  actuator:
    enabled: false
logging:
  level:
    root: error
#    root: info

---

spring:
  profiles: container
  data: # connection to linked container
    mongodb:
      uri: mongodb://greedy-mongo

---

spring:
  profiles: dev
  devtools: # additional path for watching
    restart:
      additional-paths: src/main/scala
endpoints: # enable actuator and shutdown endpoint
  shutdown:
    enabled: true
    sensitive: false
logging:
  level:
    root: info


# spring logging level example
#logging:
#  level:
#    org:
#      kduda:
#        greedy: info
#    root: error