spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
endpoints:
  actuator:
    enabled: false

---

spring:
  profiles: dev
  devtools:
    restart:
      additional-paths: src/main/scala
endpoints:
  shutdown:
    enabled: true
    sensitive: false