spring:
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      database: greedy
      grid-fs-database: greedy
endpoints: # disable actuator in production
  actuator:
    enabled: false

---

spring:
  profiles: container
  data: # connection to linked container
    mongodb:
      uri: mongodb://greedy-mongo

---

spring:
  profiles: dev
  devtools: # additional path for watching
    restart:
      additional-paths: src/main/scala
endpoints: # enable actuator and shutdown endpoint
  shutdown:
    enabled: true
    sensitive: false
