spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: false
endpoints:
  actuator:
    enabled: false

---

spring:
  profiles: dev
  devtools:
    restart:
      additional-paths: src/main/scala
endpoints:
  shutdown:
    enabled: true
    sensitive: false